### ISSUE TITLE
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

### ISSUE THREAD

**Issue by sonnv174** [Vegeta2020/CIA-SSD#8] opened 2021-04-07 03:45 UTC
I got this error when installing
`error: command 'x86_64-linux-gnu-gcc' failed with exit status 1`

**Comment by Vegeta2020** [comment] 2021-04-08 12:12
@sonnv174 I cannot debug it with such little information, it may be caused by many reasons. But I suggest you to do more check on your installation of gcc and spconv, usually, the bug could be fixed by reinstallation of these modles. Please refer to Det3D for  the installation guidance.

**Comment by mohamedgamal7** [comment] 2021-04-11 07:30
> I got this error when installing
> `error: command 'x86_64-linux-gnu-gcc' failed with exit status 1`

I have had the same error using google colab, these setups managed to solve it ,you can modify it to match your env .
```
% cd /content/
% cd /content/CIA_SSD/cia/
!pip install -r requirements.txt
!pip install gdown
!apt-get install python3.6
!apt-get install python3.6-dev
% cd /content/CIA_SSD/cia/det3d/core/iou3d
! python setup.py install
%cd /content/
!git clone https://github.com/poodarchu/Det3D.git
%cd Det3D
!pip install -r requirements.txt
%cd /content/CIA_SSD/cia/
!pip install nuscenes-devkit
!python setup.py build develop
! pip install cmake==3.13.0
! sudo apt-get install libboost-all-dev
%cd /content/
! git clone https://github.com/poodarchu/spconv --recursive
! cd spconv && python setup.py bdist_wheel
! cd /content/spconv/dist && pip install *
!pip install torchvision==0.9.0
%cd /content/
!git clone https://www.github.com/nvidia/apex
%cd apex
!python setup.py install
% cd /content/CIA_SSD/cia/det3d/core/iou3d
! python setup.py develop 
```

**Comment by fate55** [comment] 2021-08-19 13:06
For me the origin of this error was "AT_CHECK". After I added following lines into the respective src files, the error was solved: 

#ifndef AT_CHECK
#define AT_CHECK TORCH_CHECK 
#endif

ref: https://github.com/mrlooi/rotated_maskrcnn/issues/31

**Closed as completed** 2021-11-25 05:45 UTC
